CREATE TABLE vampirus_yandex
(
	BILL_ID		INT(11)		NOT NULL  AUTO_INCREMENT,
	ORDER_ID		INT(11)  NOT NULL,
	PAY		INT(1)	NOT	NULL,
	SUM DECIMAL(10,2) NOT NULL,
	INDEX (ORDER_ID),
	PRIMARY KEY (BILL_ID)
);
